# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bunkerhill/proto/inference.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n bunkerhill/proto/inference.proto\x12\nbhpy.proto\"6\n\x10InferenceRequest\x12\x14\n\x0c\x64\x61ta_dirname\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\"\x13\n\x11InferenceResponse2c\n\x12InferenceProcessor\x12M\n\x0cRunInference\x12\x1c.bhpy.proto.InferenceRequest\x1a\x1d.bhpy.proto.InferenceResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bunkerhill.proto.inference_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFERENCEREQUEST._serialized_start=48
  _INFERENCEREQUEST._serialized_end=102
  _INFERENCERESPONSE._serialized_start=104
  _INFERENCERESPONSE._serialized_end=123
  _INFERENCEPROCESSOR._serialized_start=125
  _INFERENCEPROCESSOR._serialized_end=224
# @@protoc_insertion_point(module_scope)
