"""Base model interface supported by Bunkerhill's inference pipeline."""

from typing import Any

import abc

from bunkerhill.bunkerhill_types import Outputs


class BaseModel(abc.ABC):
  """The base interface for a model that support inference()"""

  @abc.abstractmethod
  def inference(self, **kwargs: Any) -> Outputs:
    """Runs inference on the pixel array for a DICOM series.

    Args:
      **kwargs: Input attributes required for model inference.

    Returns:
      A dict of outputs generated by model inference.
    """
