# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from bunkerhill.proto import inference_pb2 as bunkerhill_dot_proto_dot_inference__pb2


class InferenceProcessorStub(object):
    """The Inference Processor service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunInference = channel.unary_unary(
                '/bhpy.proto.InferenceProcessor/RunInference',
                request_serializer=bunkerhill_dot_proto_dot_inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=bunkerhill_dot_proto_dot_inference__pb2.InferenceResponse.FromString,
                )


class InferenceProcessorServicer(object):
    """The Inference Processor service definition.
    """

    def RunInference(self, request, context):
        """Sends request to the ModelRunner to run inference.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunInference': grpc.unary_unary_rpc_method_handler(
                    servicer.RunInference,
                    request_deserializer=bunkerhill_dot_proto_dot_inference__pb2.InferenceRequest.FromString,
                    response_serializer=bunkerhill_dot_proto_dot_inference__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bhpy.proto.InferenceProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InferenceProcessor(object):
    """The Inference Processor service definition.
    """

    @staticmethod
    def RunInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bhpy.proto.InferenceProcessor/RunInference',
            bunkerhill_dot_proto_dot_inference__pb2.InferenceRequest.SerializeToString,
            bunkerhill_dot_proto_dot_inference__pb2.InferenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
